---
abstract: 'Generate random die rolls for RPGs (et al)'
author:
  - 'Buddy Burden  C<< barefootcoder@gmail.com >>'
build_requires:
  ExtUtils::MakeMaker: 6.56
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.56
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-RollDice
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.50_01
